# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-04 01:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parse_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Queryset',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('var', models.CharField(max_length=100)),
                ('year', models.IntegerField()),
            ],
        ),
    ]
