# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-04 04:49
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('parse_app', '0002_queryset'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Queryset',
            new_name='Queryvar',
        ),
    ]
